meta_product_name: "Weazr"
meta_title: "Weazr - Communicate at the right time "
meta_description: "Optimise your communication with predictive weather forecast "
meta_image: "screen-weazr.png"
twitter_account: "@product_twitter_account"
